version: '3'

services:
  app:
    container_name: payment-api
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '8080:8080'
    links:
      - mongo
      - redis
  
  worker:
    container_name: service_worker_1
    restart: unless-stopped
    build:
      context: ./
      dockerfile: "Dockerfile-worker"
    volumes:
      - .:/usr/src/app-workers
    ports:
      - '6000:6000'
    links:
      - mongo
      - redis

  redis:
    image: 'bitnami/redis:latest'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis'

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

volumes:
  redis_data:
    driver: local
